use_frameworks!

target 'DotUserDefaults_Example' do
  pod 'DotUserDefaults', :path => '../'
end

target 'DotUserDefaults_Tests' do
  pod 'DotUserDefaults', :path => '../'

  pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
end
