language: objective-c
osx_image: xcode7.3

cache:
  - bundler
  - cocoapods

xcode_workspace: Example/DotUserDefaults.xcworkspace
xcode_scheme: DotUserDefaults-Example
podfile: Example/Podfile

before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -workspace Example/DotUserDefaults.xcworkspace -scheme DotUserDefaults-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
